### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by XTCarnage** [netquik/CnCTA-SoO-SCRIPT-PACK#10]
Hey, told me to get in touch with you on github when I asked on forums, not sure how you send messages in github? 😛 
Is there a game API documentation that you navigate through? Where do you get all the information to code through the game API?
@netquik

**Comment by netquik** [comment]
Hi @XTCarnage ... well actually i get the code from browser console. All names of functiontions changes "per world" so that is the main difficulty to have a script that works for all worlds and all versions of the game. I did that for many years so i can move quite easily in the code. There are some references but they are obsolete. If you want to help you can choose a script and play with it trying to understand if it fails and where. it is a very difficult world since we have to study and fix code that we did not create. Let me know. The main problems as for 22.3 patches is adapting all regex codes to match correct methods on every worlds.

**Comment by netquik** [comment]
Note that there are many scripts that simply don't work anymore since time. that is mostly because the game changed a loto overtime. I'm working to remove and dismiss obsolete scripts. So we can focus on useful ones. Cheers and thanks.

**Comment by XTCarnage** [comment]
@netquik I see, well, this is gonna take time to get used to.
On another note, as I'm more experienced on web-part of things, I could offer you a hand to collaborate on something new? I don't know if you'd be up for that.
Ideally you could handle the game-end scripts to handle gathering player-relevant data and transfer it to a web server and I'll handle that side of things where we can implement tremendous amount of features from base optimization to alliance management et cetera.
What do you think? @netquik Let me know :D
